---
title: "Linear regression with a multiple predictors II"
subtitle: "Lecture 17"
date: "June 10, 2024"
format: 
  revealjs:
    self-contained: true
    footer: "[🔗 sta199-summer24.github.io](https://sta199-s24.github.io/) &nbsp;·&nbsp; [❓ Ask on Ed](https://edstem.org/us/courses/59071/discussion/)"
execute: 
  echo: true
editor_options: 
  chunk_output_type: console
---


```{r}
#| echo: false
#| message: false

library(countdown)
library(tidyverse)
ggplot2::theme_set(theme_gray(base_size = 16))
```

## Announcements

- June 12 is the last day to withdraw from the class.
- If you are struggling, please attend office hours and ask questions on Ed!
- Feel free to ask questions regarding Exam 1 on Ed.

## Lab 4 recap- interpreting log() response {.smaller}

Goal: Interpret the coefficients based on the following regression:

$$
\log(Y) = \beta_0 + \beta_1 x_1 + \beta_2 x_2 +\cdots.
$$
We don't want our interpretation based on the $\log()$ scale:

$$
e^{\log(Y)} = Y = e^{ \beta_0} e^{ \beta_1 x_1}e^{ \beta_2 x_2 }e^{ \cdots}.
$$
So, say we want to interpret $\beta_2$ where $x_2$ is a categorical group membership variable:
$$
Y = e^{ \beta_0} e^{ \beta_1 x_1}\color{red}{e^{ \beta_2 \times 1 }}e^{ \cdots}.
$$

## Application exercise: `ae-12` {.smaller}

::: appex
-   Let's finish AE-12!
:::


# Model selection and overfitting

## Goals

-   Review prediction and interpretation of model results
-   Review main and interaction effects models
-   Discuss model selection further

## Application exercise: `ae-13-modeling-loans` {.smaller}

::: appex
-   Go to your project called `ae`.
-   If there are any uncommitted files, commit them, and push.
-   Work on `ae-13-modeling-loans.qmd`.
:::
