```{r} #| echo: false #| message: false library(countdown) library(tidyverse) ggplot2::theme_set(theme_gray(base_size = 16)) ``` ## Announcements - Take a look at keys for labs even if you got good marks. This will give you a holistic idea of concepts you should be understanding. # Questions from last time {.smaller} ## `augment()` - Setup ```{r} #| message: false library(tidyverse) library(tidymodels) mtcars_fit <- linear_reg() |> fit(mpg ~ disp + cyl, data = mtcars) tidy(mtcars_fit) ``` ## `augment()` - Augment the original data {.smaller} ```{r} augment(mtcars_fit, new_data = mtcars) ``` ## `augment()` - Augment new data ```{r} new_cars <- tibble( mpg = c(23, 22), disp = c(150, 350), cyl = c(4, 6) ) new_cars ``` . . . ```{r} augment(mtcars_fit, new_data = new_cars) ``` ## What is the difference between $R^2$ and adjusted $R^2$? {.smaller} - $R^2$: - Proportion of variability in the outcome explained by the model. - Useful for quantifying the fit of a given model. . . . - Adjusted $R^2$: - Proportion of variability in the outcome explained by the model, with a penalty added for the number of predictors in the model. - Useful for comparing models. # AE 13 recap **Goals:** - Review prediction and interpretation of model results - Review main and interaction effects models - Discuss model selection further ## Recap: `ae-13-modeling-loans` - What is the practical difference between a model with parallel and non-parallel lines? - What is the definition of R-squared? - Why do we choose models based on adjusted R-squared and not R-squared?