---
title: "Customizing Quarto reports and presentations"
subtitle: "Lecture 24"
date: "June 18, 2024"
format: 
  revealjs:
    self-contained: true
    footer: "[ðŸ”— sta199-summer24.github.io](https://sta199-s24.github.io/) &nbsp;Â·&nbsp; [â“ Ask on Ed](https://edstem.org/us/courses/59071/discussion/)"
execute: 
  echo: true
editor_options: 
  chunk_output_type: console
---


## Before we get started {.smaller}

::: question
-   Go to your `ae` repo, and pull.

-   Make a change, any change, to `ae-18-second-to-last-ae.qmd`.
    render, commit, and push.
:::


## Project presentations on Monday! ðŸ¥³ {.smaller}

-   Make sure your presentation is pushed to your GitHub repo before your lab section.

-   Get to lab on time, 5 minutes prior if possible -- **all team members must be present in class and take part in the presentation + Q&A**

-   Find out your presentation order when you get there.

-   Deliver your 5-minute presentation 

-   Answer questions during your own Q&A or ask questions to others.

-   Fill out feedback forms while you listen to others' presentations.

## Project write-ups due Monday evening

-   There's a good chance you'll be done with these on Monday as well

-   But you might want to improve your write-up based on inspiration from other teams' presentations and/or ideas that came up during your Q&A.

-   There is no Gradescope submission, just push your final edits to GitHub.

# Questions from last time

## Expectations {.smaller}

> The goal of this project is for you to demonstrate proficiency in the techniques we have covered in this class (and beyond, if you like) and apply them to a novel dataset in a meaningful way.

::: callout-note
Beyond, if you like -- "you" is the whole team!
:::

<br>

::: callout-important
## Read more

<https://sta199-summer24.github.io/project/>
:::

## Expectations {.smaller}

> The goal is not to do an exhaustive data analysis i.e., do not calculate every statistic and procedure you have learned for every variable, but rather let me know that you are proficient at asking meaningful questions and answering them with results of data analysis, that you are proficient in using R, and that you are proficient at interpreting and presenting the results.

<br>



## Requirements

> Focus on methods that help you begin to answer your research questions.
> You do not have to apply every statistical procedure we learned.

## Tip {.smaller}

> Critique your own methods and provide suggestions for improving your analysis.
> Discuss issues pertaining to the reliability and validity of your data, and appropriateness of the statistical analysis.

::: callout-tip
You can critique the current research without talking about a hypothetical future research,.
:::

<br>


## How many plots {.smaller}

> You do not need to visualize all of the data at once.
> A single high-quality visualization will receive a much higher grade than a large number of poor-quality visualizations.

::: callout-note
There is no specific, secret number of visualizations I'm expecting, the right number is the number that it takes to answer your question.
:::


## Submission {.smaller}

> You will not be submitting anything on Gradescope for the project.
> Submission of these deliverables will happen on GitHub.



## Writeup {.smaller}

::: question
-   Is there any paper that is required as well as the presentation?
-   What is the project write up?
-   Are write ups usually around the 10 page limit?
-   Is there a recommended outline to the project?
:::




## Something else ðŸ’› {.smaller}

::: question
I have enjoyed this semester, and I want to continue learning R.
What classes do you recommend I take to continue my learning?
:::

-   STA 323: Statistical computing - R as a programming language

-   STA 210: Regression analysis - for anyone interested in applications

-   STA 221: Regression analysis - for majors + minors + anyone interested in the theory as well as applications

# Code review

-   [Data Alchemy Hub](https://github.com/sta199-s24/project-data_alch)
-   [Tidyverse Tibbles](https://github.com/sta199-s24/project-tidyverse_tibbles)
-   [Data Dream Team](https://github.com/sta199-s24/project-data_dream_team)
-   [smaRt Water](https://github.com/sta199-s24/project-smaRt_water)

# Quarto demo / Code review recap

## Your project write-up with Quarto {.smaller}

-   Figure sizing: `fig-width`, `fig-height`, etc. in code chunks.

-   Figure layout: `layout-ncol` for placing multiple figures in a chunk.

-   Further control over figure layout with the **patchwork** package.

-   Chunk options around what makes it in your final report: `message`, `echo`, etc.

-   Citations.

-   Finalizing your report with `echo: false`.


## Before you leave {.smaller}

if you haven't yet done so...

::: question
-   Go to your `ae` repo, and pull.

-   Make a change, any change, to `ae-18-second-to-last-ae.qmd`.
    render, commit, and push.
:::
